const mongoose = require('mongoose');
const ObjectId = mongoose.Schema.Types.ObjectId;

const paymentSchema = new mongoose.Schema({

    userId: {
        type: ObjectId,
        ref: "User",
        required: true,
        index: true
    },

    planId: {
        type: ObjectId,
        ref: "Plan",
        required: true,
        index: true
    },

    amount: {
        type: Number,
        required: true,
        min: 0
    },

    currency: {
        type: String,
        default: "INR"
    },

    status: {
        type: String,
        enum: ["pending", "success", "failed"],
        default: "pending",
        index: true
    },

    provider: {
        type: String,
        enum: ["cashfree"],
        default: "cashfree"
    },

    /* order id generated by your system */
    orderId: {
        type: String,
        required: true,
        unique: true,
        index: true
    },

    /* order id returned by gateway */
    providerOrderId: {
        type: String,
        index: true
    },

    /* payment id returned by gateway */
    providerPaymentId: {
        type: String,
        index: true
    },

    webhookProcessed: {
        type: Boolean,
        default: false,
        index: true
    },

    failureReason: {
        type: String
    },

    metadata: {
        type: mongoose.Schema.Types.Mixed,
        default: {}
    }

}, { timestamps: true });

module.exports = mongoose.model('Payment', paymentSchema);